server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/airline_ticket_manager
        username: airline_manager_user
        password: 1234
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create
        show-sql: false
#    security:
#      oauth2:
#        resourceserver:
#            jwt:
#                issuer-uri: http://localhost:8080/auth/realms/SpringBootKeycloak
#                jwk-set-uri: http://localhost:8080/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs
logging:
    level:
        com.airline.airlineticketmanager: info
#        com.airline.airlineticketmanager.config: debug

# App Properties
jwtCookieName: atmb
jwtSecret: atmbSecretKey
jwtExpirationMs: 86400000
API_PATH: /api
management.endpoints.web.base-path: /manage
server.error.include-stacktrace: never
