spring:
    datasource:
        url: jdbc:mysql://localhost:3306/airline_ticket_manager
        username: airline_manager_user
        password: 1234
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: false
logging:
    level:
        com.airline.airlineticketmanager: info

API_PATH: /api
management.endpoints.web.base-path: /manage
server.error.include-stacktrace: never
