spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
logging:
    level:
        com.airline.airlineticketmanager: info
        root: error
customProp: hello world
