server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/airline_ticket_manager
        username: airline_manager_user
        password: 1234
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: false
#    security:
#      oauth2:
#        resourceserver:
#            jwt:
#                issuer-uri: http://localhost:8080/auth/realms/SpringBootKeycloak
#                jwk-set-uri: http://localhost:8080/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs
logging:
    level:
        com.airline.airlineticketmanager: info
#        com.airline.airlineticketmanager.config: debug

# Custom App Properties
API_PATH: /api
AUTH_PATH: /auth
management.endpoints.web.base-path: /manage
server.error.include-stacktrace: never
authoritiesByUsernameQuery: select u.username, r.name from users u inner join user_roles ur on ur.user_id = u.id and u.username = ? inner join roles r on r.id = ur.role_id
jwtCookieName: atmb
jwtSecret: atmbSecretKey
jwtExpirationMs: 86400000
